config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: {
    registrations: 'customers/registrations'
  }

  get 'welcome/index'

  resources :wines, only: [:index, :show]
  resources :basket, only: [:index, :create, :update, :destroy]
  resources :checkout, only: [:create]

  delete 'basket' => 'basket#destroy', :as => :basket_destroy

  root 'welcome#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :wines
end

app/models/wine.rb
class Wine < ActiveRecord::Base
  belongs_to :supplier

  validates :title, :size, :price, :country, :grape_type, presence: true
  validates :price, numericality: { greater_than: 0 }

  ##
  # Search through all of the available wines and fetch the ones that partially
  # match a given string
  #
  # +query+ contains a string to search for
  def self.search(query)
    where 'title LIKE ? OR country LIKE ? OR description LIKE ?',
      "%#{query}%", "%#{query}%", "%#{query}%"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
  def index
    @basket = session[:basket]
  end

  def create
    add params[:basket]

    redirect_to basket_index_path
  end

  def update
    # TODO
    #Basket.add params[:basket]
    redirect_to basket_index_path
  end

  def destroy
    if params[:wine]
      session[:basket].delete params[:wine]
    else
      session[:basket].clear
    end

    redirect_to basket_index_path
  end

  private
  ##
  # If the basket does not exist in the session, create it with an empty hash
  def create_if_not_existing
    if !session.has_key? :basket
      session[:basket] = {}
    end
  end

  ##
  # Add an order to the basket with the wine id as the key and the quantity as
  # the value
  #
  # +order+ is a form submission of a wine to be added to the basket
  def add(order)
    create_if_not_existing

    # The form submits the param keys as strings, so we need to convert them
    # into symbols
    order.symbolize_keys
    session[:basket][order[:wine]] = order[:quantity].to_i
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :authenticate_customer!

  def create
    submit_orders_to_suppliers current_customer, list_orders(session[:basket])

    redirect_to basket_index_path
  end

  private
  ##
  # Convert the +basket+ from the visitor's session into a hash of an
  # ActiveRecord of the wine and the quantity being ordered.
  def list_orders(basket)
    basket.inject([]) do |orders, (id, quantity)|
      orders << {
        wine: Wine.find(id),
        quantity: quantity
      }
    end
  end

  ##
  # Submits the orders to all of the suppliers.
  #
  # +customer+ is the ActiveRecord of a Customer
  # +orders+ is an array of hashes containing the user's orders
  def submit_orders_to_suppliers(customer, orders)
    raise ArgumentError unless customer.is_a? Customer and orders.is_a? Array

    # Submit each wine order to the revelant supplier
    orders.each do |order|
      RestClient.post "#{order[:wine].supplier.url}orders", {
        name: customer.name,
        address: customer.address,
        email: customer.email,
        upc: order[:wine].upc,
        quantity: order[:quantity]
      }.to_json, content_type: :json do |response|
        case response.code
        when 200, 201
          session[:basket].clear
        else
          #TODO: log an error
          puts 'error oh nooooo'
        end
      end
    end
  end
end

app/controllers/customers/registrations_controller.rb
class Customers::RegistrationsController < Devise::RegistrationsController
before_filter :configure_sign_up_params, only: [:create]
before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:sign_up) << :address
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :name
    devise_parameter_sanitizer.for(:account_update) << :address
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  require 'rest-client'

  def index
    #XXX: Temporary until this can be added to a cron or scheduler
    SyncWithSuppliersJob.perform_now

    if params[:search]
      @wines = Wine.search(params[:search])
    else
      @wines = Wine.all
    end
  end

  def show
    @wine = Wine.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/basket/index.html.erb
<section>
  <h1>Basket</h1>

  <% if !@basket.nil? and !@basket.empty? %>
    <table>
      <thead>
        <tr>
          <th>Wine</th>
          <th>Quantity</th>
          <th>Price</th>
          <th></th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td colspan="2">Total</td>
          <td><% """@total TODO""" %></td>
        </tr>
      </tfoot>
      <tbody>
        <% @basket.each do |wine_id, quantity| %>
          <% wine = Wine.find(wine_id) %>

          <tr>
            <td><%= wine.title %></td>
            <td><%= quantity %></td>
            <td>£<%= format '%.2f', wine.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <p><%= link_to "Delete", basket_destroy_path, method: :delete %></p>

    <%= form_for :orders, url: {controller: 'checkout', action: 'create'} do |form| %>
      <p><%= form.submit 'Checkout' %></p>
    <% end %>
  <% else %>
    <p>There is nothing in your basket.</p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en-gb">
<head>
  <meta charset="utf-8">
  <title>My Alcohol-Free Wine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <h1>My Alcohol-Free Wine</h1>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Wine selection', wines_path %></li>
        <li><%= link_to 'Basket', basket_index_path %></li>
        <% if customer_signed_in? %>
        <li><%= link_to 'Edit account', edit_customer_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_customer_session_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_customer_session_path %></li>
          <li><%= link_to 'Register', new_customer_registration_path %></li>
        <% end %>
      </ul>

      <%= form_tag wines_path, method: "get" do %>
        <%= label_tag :search, "Search:" %>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Go" %>
      <% end %>
    </nav>
  </header>

  <main>
    <%= yield %>
  </main>

  <footer>
    <p>&copy; 2015 Josh Tumath</p>
  </footer>

</body>
</html>

app/views/welcome/index.html.erb
Welcome

<h2>Credits</h2>
<p>
  <a href="https://www.flickr.com/photos/davedugdale/5187439576/">Wine Bottle
  Rack</a> by Dave Dugdale (CC BY-SA)
</p>

app/views/wines/index.html.erb
<h1>Listing wines</h1>

<% if @wines.present? %>
<ul class="wines">
  <% @wines.each do |wine| %>
  <li>
    <article>
      <a href="<%= wine_path wine %>">
        <h1><%= wine.title %></h1>
        <img src="/images/wines/<%= wine.upc %>.jpg" alt="">

        <p class="price">£<%= format "%.2f", wine.price %></p>
        <p><%= wine.size %> ml</p>
        <p class="supplier">Supplied by <i><%= wine.supplier.name %></i></p>
      </a>
    </article>
  </li>
  <% end %>
</ul>
<% elsif params[:search] %>
  <p>There are no wines that match your search.</p>
<% else %>
  <p>There are no wines available at the moment. Please check back later.</p>
<% end %>

app/views/wines/show.html.erb
<article class="col-container">
  <h1><%= @wine.title %></h1>

  <div class="col">
    <img src="/images/wines/<%= @wine.upc %>.jpg" alt="">

    <p>£<%= format '%.2f', @wine.price %></p>
  </div>

  <div class="col">
    <dl>
      <dt>Country of origin</dt>
      <dd><%= @wine.country %></dd>

      <dt>Grape type</dt>
      <dd><%= @wine.grape_type %></dd>

      <dt>Vegetarian</dt>
      <dd><%= @wine.vegetarian %></dd>

      <dt>Bottle size</dt>
      <dd><%= @wine.size %> ml</dd>

      <dt>Supplier</dt>
      <dd><%= @wine.supplier.name %></dd>
    </dl>

    <%= form_for :basket, url: {controller: 'basket', action: 'create'} do |form| %>
      <%= hidden_field_tag 'basket[wine]', @wine.id %>

      <%= form.label :quantity, 'Quantity:' %>
      <%= form.number_field :quantity, value: 1, min: 1 %>
      <%= form.submit 'Add to basket' %>
    <% end %>

    <p><%= @wine.description %></p>
  </div>
</article>

<%= link_to 'Back', wines_path %>